### ISSUE TITLE
Image Picker

### ISSUE THREAD

**Issue by maulananurkarim** [Zignake/Flutter-TfLite#1]
Image Picker not working on image_picker 0.6.7+14

reference: https://pub.dev/packages/image_picker

**Comment by Zignake** [comment]
Sorry for the delayed response. Yes, it is deprecated in the latter versions and even I used to get warnings. But as it worked nevertheless I didn't do anything regarding it. Thanks for pointing it out, I'll look into it. For the time being, you can use the previous version of image_picker.

**Comment by laukikk** [comment]
> Image Picker not working on image_picker 0.6.7+14
> 
> reference: https://pub.dev/packages/image_picker

Sorry for the delayed response. Yes, it is deprecated in the latter versions and even I used to get warnings. But as it worked nevertheless I didn't do anything regarding it. Thanks for pointing it out, I'll look into it. For the time being, you can use the previous version of image_picker.

**Comment by laukikk** [comment]
@maulananurkarim resolved the issue by using the newer version of the deprecated function
